### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by zfhxi** [mathewthe2/AnkiCloud#1]
Hello, nice job, but I don't know how to use it. Is there a manual or something?

**Comment by mathewthe2** [comment]
It was an experiment that I started but never completed.

Main issues are 
1. saving passwords (meaning you'll have to re-login with your password every time)
2. data structure. Sqlite and db files are not recommended to be used on icloud, while implementing database updates, migrations, and sync are a lot of work.

The spiritual successor of this project is [Anki Dojo](https://github.com/mathewthe2/AnkiDojo).
